# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1062, 773)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1061, 751))
        self.tabWidget.setMinimumSize(QtCore.QSize(1061, 0))
        self.tabWidget.setStyleSheet("QTabBar::tab { height: 40;width: 530px; }")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setMinimumSize(QtCore.QSize(1055, 0))
        self.tab.setBaseSize(QtCore.QSize(0, 0))
        self.tab.setObjectName("tab")
        self.run_btn = QtWidgets.QPushButton(self.tab)
        self.run_btn.setGeometry(QtCore.QRect(420, 620, 211, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.run_btn.setFont(font)
        self.run_btn.setObjectName("run_btn")
        self.proc_combo = QtWidgets.QComboBox(self.tab)
        self.proc_combo.setGeometry(QtCore.QRect(10, 0, 1031, 91))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.proc_combo.setFont(font)
        self.proc_combo.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.proc_combo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.proc_combo.setObjectName("proc_combo")
        self.proc_combo.addItem("")
        self.proc_combo.addItem("")
        self.proc_combo.addItem("")
        self.proc_combo.addItem("")
        self.proc_combo.addItem("")
        self.proc_combo.addItem("")
        self.unit_time_line = QtWidgets.QLineEdit(self.tab)
        self.unit_time_line.setGeometry(QtCore.QRect(920, 570, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.unit_time_line.setFont(font)
        self.unit_time_line.setAlignment(QtCore.Qt.AlignCenter)
        self.unit_time_line.setObjectName("unit_time_line")
        self.unit_time_lbl = QtWidgets.QLabel(self.tab)
        self.unit_time_lbl.setGeometry(QtCore.QRect(770, 570, 141, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.unit_time_lbl.setFont(font)
        self.unit_time_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.unit_time_lbl.setObjectName("unit_time_lbl")
        self.clear_btn = QtWidgets.QPushButton(self.tab)
        self.clear_btn.setGeometry(QtCore.QRect(10, 620, 211, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.clear_btn.setFont(font)
        self.clear_btn.setObjectName("clear_btn")
        self.load_btn = QtWidgets.QPushButton(self.tab)
        self.load_btn.setGeometry(QtCore.QRect(830, 620, 211, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.load_btn.setFont(font)
        self.load_btn.setObjectName("load_btn")
        self.input_text = QtWidgets.QPlainTextEdit(self.tab)
        self.input_text.setGeometry(QtCore.QRect(10, 100, 501, 351))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.input_text.setFont(font)
        self.input_text.setPlainText("")
        self.input_text.setObjectName("input_text")
        self.info_text = QtWidgets.QTextBrowser(self.tab)
        self.info_text.setGeometry(QtCore.QRect(540, 100, 501, 351))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info_text.setFont(font)
        self.info_text.setStyleSheet("")
        self.info_text.setObjectName("info_text")
        self.warning_text = QtWidgets.QTextBrowser(self.tab)
        self.warning_text.setGeometry(QtCore.QRect(10, 460, 1031, 101))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.warning_text.setFont(font)
        self.warning_text.setObjectName("warning_text")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.graphs_combo = QtWidgets.QComboBox(self.tab_2)
        self.graphs_combo.setGeometry(QtCore.QRect(10, 0, 1031, 91))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.graphs_combo.setFont(font)
        self.graphs_combo.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.graphs_combo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.graphs_combo.setObjectName("graphs_combo")
        self.graphs_combo.addItem("")
        self.graphs_combo.addItem("")
        self.graphs_combo.addItem("")
        self.options_combo = QtWidgets.QComboBox(self.tab_2)
        self.options_combo.setGeometry(QtCore.QRect(750, 110, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.options_combo.setFont(font)
        self.options_combo.setObjectName("options_combo")
        self.options_combo.addItem("")
        self.options_combo.addItem("")
        self.draw_btn = QtWidgets.QPushButton(self.tab_2)
        self.draw_btn.setGeometry(QtCore.QRect(10, 620, 1031, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.draw_btn.setFont(font)
        self.draw_btn.setObjectName("draw_btn")
        self.graph_text = QtWidgets.QTextBrowser(self.tab_2)
        self.graph_text.setGeometry(QtCore.QRect(750, 180, 291, 421))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.graph_text.setFont(font)
        self.graph_text.setObjectName("graph_text")
        self.graph_area = QtWidgets.QLabel(self.tab_2)
        self.graph_area.setEnabled(True)
        self.graph_area.setGeometry(QtCore.QRect(10, 100, 721, 511))
        self.graph_area.setText("")
        self.graph_area.setScaledContents(False)
        self.graph_area.setObjectName("graph_area")
        self.graphs_combo.raise_()
        self.draw_btn.raise_()
        self.options_combo.raise_()
        self.graph_text.raise_()
        self.graph_area.raise_()
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1062, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CPU Scheduler"))
        self.run_btn.setText(_translate("MainWindow", "Run"))
        self.proc_combo.setItemText(0, _translate("MainWindow", "FCFS"))
        self.proc_combo.setItemText(1, _translate("MainWindow", "SJF Preemptive"))
        self.proc_combo.setItemText(2, _translate("MainWindow", "SJF Non-Preemptive"))
        self.proc_combo.setItemText(3, _translate("MainWindow", "Priority Preemptive"))
        self.proc_combo.setItemText(4, _translate("MainWindow", "Priority Non-Preemptive"))
        self.proc_combo.setItemText(5, _translate("MainWindow", "Round Robin"))
        self.unit_time_line.setText(_translate("MainWindow", "0.1"))
        self.unit_time_lbl.setText(_translate("MainWindow", "unit time:"))
        self.clear_btn.setText(_translate("MainWindow", "Clear"))
        self.load_btn.setText(_translate("MainWindow", "Load"))
        self.info_text.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt;\"><br /></p></body></html>"))
        self.warning_text.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt;\"><br /></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Scheduling"))
        self.graphs_combo.setItemText(0, _translate("MainWindow", "Gantt Chart"))
        self.graphs_combo.setItemText(1, _translate("MainWindow", "Pie Chart"))
        self.graphs_combo.setItemText(2, _translate("MainWindow", "Bar Chart"))
        self.options_combo.setItemText(0, _translate("MainWindow", "Different Colors"))
        self.options_combo.setItemText(1, _translate("MainWindow", "One Color"))
        self.draw_btn.setText(_translate("MainWindow", "Draw"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Graphs"))

